name: github pages

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout project
        uses: actions/checkout@v2
        with:
          submodules: true  # Fetch Hugo themes (true OR recursive)
          fetch-depth: 0    # Fetch all history for .GitInfo and .Lastmod

      - name: Substitute PLACEHOLDER_USERNAME and PLACEHOLDER_REPOSITORY_NAME in config.toml
        run: |
          REPOSITORY_NAME=${{ github.event.repository.name}}
          USERNAME=${{ github.repository_owner }}
          sed -i "s|PLACEHOLDER_USERNAME|$USERNAME|g" config.toml
          sed -i "s|PLACEHOLDER_REPOSITORY_NAME|$REPOSITORY_NAME|g" config.toml

      - name: Setup Hugo
        uses: peaceiris/actions-hugo@v2
        with:
          hugo-version: 'latest'
          # extended: true

      - name: Build static files
        run: hugo --minify

      - name: Deploy to GitHub pages
        uses: peaceiris/actions-gh-pages@v3
        if: github.ref == 'refs/heads/main'
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public